### PR TITLE
Wifi Logger 2 example config.

### PR DESCRIPTION
**Pull request by tomdotorg**
This config has been working for me. In our discussion, it sounds like I might be ignoring some native Weewx capabilities for cumulative fields like rain, which would be a mistake. If this example should be modified as such, I am happy to do it.

### CODE REVIEW

**Comment by bellrichm** [comment]
This is great. I haven’t had a chance to experiment with rain. If/when I do, I’ll let you know.
Are there any wifi logger settings that you want to add as a comment? Mode? Topic?

**Comment by tomdotorg** [comment]
Good idea. I added some comments on how to configure the WFL in the .conf file.

**Comment by bellrichm** [comment]
Thanks again! 
I’m getting ready to release 2.1 which makes the array/subfield support official. I will add a comment to the file stating that requirement

**Comment by tomdotorg** [comment]
Awesome. Thanks for your support through the process.

**Pull request merged**
