### PR TITLE
Introduce total_wrap_around configuration option

### PR DESCRIPTION
**Pull request by nifoc**
Allow for the detection of the wrap around of a `contains_total` field and adjust the new value accordingly.

Before this commit `current_total` being smaller than `previous_total` would result in the field being set to `None` and it would take another packet to actually calculate the difference again. This can result in some data being "lost", because the data right after the wrap around is essentially discarded.
Setting the new `total_wrap_around` option to `True` will result in `current_total` being used as the return value right away.

The option is set to `False` by default, so you have to explicitly opt-in.

Some examples:

- The `yearlyrainin` of some Ecowitt/FineOffset stations wraps around every year
- The `lightning_num` of some Ecowitt/FineOffset stations wraps around every day

### CODE REVIEW

**Comment by nifoc** [comment]
I think the AppVeyor pipeline is failing for unrelated reasons.

**Comment by bellrichm** [comment]
Agree it is unrelated. I’ll get this merged shortly.
Any interest in updating this [page](https://github.com/bellrichm/WeeWX-MQTTSubscribe/wiki/Configuring#the-field-name-sections) with a coming soon?
Thanks for the help!

**Comment by nifoc** [comment]
I don't think I can edit the wiki page. I would've added the following description:

total_wrap_around

To be used in conjunction with `contains_total`.

Set to `true` if the incoming cumulative value can wrap around (yearly rain for example). The default is `false`.

**Comment by bellrichm** [comment]
Ok.  Thanks again.

**Pull request merged**
